M48
; DRILL file KiCad 10.0.1 date 2026-05-13T19:12:59
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-13T19:12:59-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X79.88Y-160.865
X79.88Y-165.715
T2
X76.85Y-160.565
X76.85Y-166.015
M30
